replicaCount: 1
service:
  ports:
    - name: http
      port: 8080
      containerPort: 3003

ingress:
  path: /api/customer
  port: 8080

selector:
  app: customer

image:
  name: customer-service
  tag: 2

config:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres
  DATABASE_URL: jdbc:postgresql://postgres:5432/demo

secret:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: demo

migrations:
  image:
    name: customer-migrations
    tag: 2
  config:
    POSTGRES_DB: demo
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: demo
    DATABASE_URL: "jdbc:postgresql://postgres:5432/demo"