apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: auth                # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
      labels:
        app: auth               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      initContainers:
        - name: run-migrations
          image: auth-migrations:2
          command: ["sqlx", "migrate", "run", "--source", "."] # CLI команда запуску міграцій, де $(POSTGRESQL_URL) і $(VERSION) змінні середовища
          env:
            - name: DATABASE_URL
              value: "postgres://demo:demo@postgres:5432/demo?sslmode=disable"
      containers:
        - image: auth-service:2       # образ Docker
          imagePullPolicy: Never   # вказує k8s, що образ не потрібно завантажувати (варто використовувати лише для випадків, коли образи локальні)
          name: auth           # ім'я контейнеру
          ports:
            - containerPort: 3000  # порт по якому можна звертатись до поди
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
