//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "created")]
    Created,
    #[sea_orm(string_value = "delivered")]
    Delivered,
    #[sea_orm(string_value = "packaging")]
    Packaging,
    #[sea_orm(string_value = "shipping")]
    Shipping,
}
