replicaCount: 1
service:
  ports:
    - name: amqp
      port: 5672
      containerPort: 5672

selector:
  app: email

image:
  name: email-service
  tag: 5

config:
  AMQP_URL: amqp://user:user@rabbitmq:5672
  MAILGUN_API: 