replicaCount: 1

service:
  ports:
    - name: http
      port: 8080
      containerPort: 3000

ingress:
  path: /api/auth
  port: 8080

selector:
  app: auth

image:
  name: auth-service
  tag: 2

config:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres

secret:
  JWT_SECRET: d7b79c83a74b1bfed52d80df15558874
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: demo

migrations:
  image:
    name: auth-migrations
    tag: 2
  config:
    DATABASE_URL: "postgres://postgres:demo@postgres:5432/demo?sslmode=disable"