apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-config
data:
  POSTGRES_DB: customer
  POSTGRES_HOST: postgres
  DATABASE_URL: jdbc:postgresql://postgres:5432/customer?useSSL=false&serverTimezone=UTC
