apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: customers                # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
      labels:
        app: customers               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      containers:
        - image: customers:1       # образ Docker
          imagePullPolicy: Never   # вказує k8s, що образ не потрібно завантажувати (варто використовувати лише для випадків, коли образи локальні)
          name: customers           # ім'я контейнеру
          ports:
            - containerPort: 3003  # порт по якому можна звертатись до поди 
