apiVersion: v2
type: application
version: 0.0.1
name: microservices-labs
appVersion: "0.1"
description: "Microservices Labs"

dependencies:
  - name: postgresql
    version: 10.16.2
    repository: file://charts/postgresql
  - name: common
    version: 0.1.0
    repository: file://charts/common
  - name: rabbitmq
    version: 11.4.0
    repository: file://charts/rabbitmq